name: Build and Publish to DockerHub

on:
  push:
    branches: ['main']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      env:
        DOCKER_PASSWORD: ${{ dev.DOCKER_HUB_TOKEN }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sudomoon/decipher:latest

    - name: publish
      run: docker push sudomoon/decipher:latest
