name: Build and Publish to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      docker_pat: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sudomoon/decipher:latest

    - name: publish
      run: |
        echo "$${{ env.docker_pat }}" | docker login -u sudomoon --password-stdin
        docker push sudomoon/decipher:latest
