name: Build and Publish to DockerHub

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sudomoon/decipher:latest

    - name: publish
      run: docker push sudomoon/decipher:latest
